#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_60 ]
	then 
		cd $OPENSHIFT_DATA_DIR
		wget http://download.java.net/jdk8u60/archive/b10/binaries/jdk-8u60-ea-bin-b10-linux-x64-08_apr_2015.tar.gz
		tar xvf *.tar.gz 
		rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.1 ]
	then 
		cd $OPENSHIFT_DATA_DIR
		wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz		tar xvf *.tar.gz 
		rm -f *.tar.gz
fi

export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.1/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_60
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd $OPENSHIFT_REPO_DIR
mvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -q clean install
