#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x


export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.1/bin
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_60
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd $OPENSHIFT_REPO_DIR
"C:\Program Files\Java\jdk1.8.0_60\bin\java.exe" -jar diy/todoapp-1.0-SNAPSHOT.jar &
